// Builds a new .xsq from scratch. Ported from DmxWands/GenerateFloodEffect.py (SequenceGenerator).

import { promises as fs } from 'fs';
import { DOMParser } from '@xmldom/xmldom';
import { RGB, rgbToHexString } from './ColorUtil';
import { TimingRec } from './XsqTiming';

const BLACK_PALETTE_TAIL =
    'C_BUTTON_Palette2=#000000,C_BUTTON_Palette3=#000000,C_BUTTON_Palette4=#000000,C_BUTTON_Palette5=#000000,C_BUTTON_Palette6=#000000,C_BUTTON_Palette7=#000000,C_BUTTON_Palette8=#000000,C_CHECKBOX_Palette1=1';

export class XsqWriter {
    readonly doc: Document;
    private readonly root: Element;
    private readonly head: Element;
    private readonly nextid: Element;
    private readonly palettes: Element;
    private readonly effectdb: Element;
    private readonly displayElements: Element;
    private readonly elementEffects: Element;

    private readonly paletteIds = new Map<string, number>();
    private readonly paletteList: string[] = [];
    private readonly effectIds = new Map<string, number>();
    private readonly effectList: string[] = [];
    private readonly displayNames = new Set<string>();
    private readonly effectElements = new Map<string, Element>();
    private effectCounter = 0;

    constructor(readonly frameMs: number, readonly nFrames: number) {
        const durationSec = (frameMs * nFrames) / 1000.0;
        this.doc = new DOMParser().parseFromString(
            `<xsequence BaseChannel="0" ChanCtrlBasic="0" ChanCtrlColor="0" FixedPointTiming="1" ModelBlending="true">
  <head>
    <version>2026.12</version>
    <author></author>
    <author-email></author-email>
    <author-website></author-website>
    <song></song>
    <artist></artist>
    <album></album>
    <MusicURL></MusicURL>
    <comment>Generated by DmxWandsTS</comment>
    <sequenceTiming>${frameMs} ms</sequenceTiming>
    <sequenceType>Animation</sequenceType>
    <mediaFile></mediaFile>
    <sequenceDuration>${durationSec.toFixed(3)}</sequenceDuration>
    <imageDir></imageDir>
  </head>
  <nextid>1</nextid>
  <Jukebox/>
  <ColorPalettes/>
  <EffectDB/>
  <DataLayers>
    <DataLayer lor_params="0" channel_offset="0" num_channels="0" num_frames="0" data="&lt;rendered: erase-mode&gt;" source="&lt;auto-generated&gt;" name="Nutcracker"/>
  </DataLayers>
  <DisplayElements/>
  <ElementEffects/>
  <LastView>1</LastView>
  <TimingTags/>
</xsequence>`,
            'text/xml',
        ) as unknown as Document;
        this.root = this.doc.documentElement!;
        this.head = this.child(this.root, 'head');
        this.nextid = this.child(this.root, 'nextid');
        this.palettes = this.child(this.root, 'ColorPalettes');
        this.effectdb = this.child(this.root, 'EffectDB');
        this.displayElements = this.child(this.root, 'DisplayElements');
        this.elementEffects = this.child(this.root, 'ElementEffects');
    }

    private child(parent: Element, tag: string): Element {
        for (let i = 0; i < parent.childNodes.length; ++i) {
            const k = parent.childNodes[i];
            if (k.nodeType === 1 && (k as Element).tagName === tag) return k as Element;
        }
        throw new Error(`Template is missing <${tag}>`);
    }

    private setText(el: Element, text: string): void {
        while (el.firstChild) el.removeChild(el.firstChild);
        el.appendChild(this.doc.createTextNode(text));
    }

    /** Make this a media sequence pointing at the given audio file. */
    setMedia(mediaFile: string, song = '', artist = '', album = ''): void {
        this.setText(this.child(this.head, 'mediaFile'), mediaFile);
        this.setText(this.child(this.head, 'sequenceType'), 'Media');
        if (song) this.setText(this.child(this.head, 'song'), song);
        if (artist) this.setText(this.child(this.head, 'artist'), artist);
        if (album) this.setText(this.child(this.head, 'album'), album);
    }

    setComment(text: string): void {
        this.setText(this.child(this.head, 'comment'), text);
    }

    ensureDisplayElement(name: string, type: 'model' | 'timing' = 'model'): void {
        if (this.displayNames.has(name)) return;
        this.displayNames.add(name);
        const el = this.doc.createElement('Element');
        el.setAttribute('collapsed', '0');
        el.setAttribute('type', type);
        el.setAttribute('name', name);
        el.setAttribute('visible', '1');
        if (type === 'timing') {
            el.setAttribute('active', '1');
            // Timing tracks go first so xLights shows them at the top.
            this.displayElements.insertBefore(el, this.displayElements.firstChild);
        } else {
            this.displayElements.appendChild(el);
        }
    }

    private getOrCreateEffectElement(name: string, type: 'model' | 'timing' = 'model'): Element {
        let el = this.effectElements.get(name);
        if (!el) {
            el = this.doc.createElement('Element');
            el.setAttribute('type', type);
            el.setAttribute('name', name);
            this.elementEffects.appendChild(el);
            this.effectElements.set(name, el);
        }
        return el;
    }

    /** A fresh effect layer on the named model (creating its display element and effect element as needed). */
    addEffectLayer(modelName: string): Element {
        this.ensureDisplayElement(modelName, 'model');
        const el = this.getOrCreateEffectElement(modelName, 'model');
        const layer = this.doc.createElement('EffectLayer');
        el.appendChild(layer);
        return layer;
    }

    /** Copy a timing track into the output so the generated changes can be reviewed against it. */
    addTimingTrack(track: TimingRec): void {
        this.ensureDisplayElement(track.name, 'timing');
        const el = this.getOrCreateEffectElement(track.name, 'timing');
        const layers = track.subentlists.length ? track.subentlists : [track.entlist];
        for (const ents of layers) {
            const layer = this.doc.createElement('EffectLayer');
            el.appendChild(layer);
            for (const te of ents) {
                const eff = this.doc.createElement('Effect');
                eff.setAttribute('label', te.label);
                eff.setAttribute('startTime', `${te.startms}`);
                eff.setAttribute('endTime', `${te.endms}`);
                layer.appendChild(eff);
            }
        }
    }

    private intern(map: Map<string, number>, list: string[], data: string): number {
        let id = map.get(data);
        if (id === undefined) {
            id = list.length;
            list.push(data);
            map.set(data, id);
        }
        return id;
    }

    addEffect(layer: Element, name: string, startMs: number, endMs: number, effectData: string, paletteData: string): Element {
        const eff = this.doc.createElement('Effect');
        eff.setAttribute('ref', `${this.intern(this.effectIds, this.effectList, effectData)}`);
        eff.setAttribute('name', name);
        eff.setAttribute('startTime', `${Math.round(startMs)}`);
        eff.setAttribute('endTime', `${Math.round(endMs)}`);
        eff.setAttribute('palette', `${this.intern(this.paletteIds, this.paletteList, paletteData)}`);
        layer.appendChild(eff);
        ++this.effectCounter;
        return eff;
    }

    /** Solid "On" effect in one color. `perModel` renders per model when the target is a group. */
    addOnEffect(layer: Element, startMs: number, endMs: number, rgb: RGB, perModel = false): Element {
        const pdata = `C_BUTTON_Palette1=${rgbToHexString(rgb)},${BLACK_PALETTE_TAIL}`;
        const edata = `${perModel ? 'B_CHOICE_BufferStyle=Per Model Default Deep,' : ''}E_TEXTCTRL_Eff_On_Start=100,E_TEXTCTRL_Eff_On_End=100,E_TEXTCTRL_On_Cycles=1`;
        return this.addEffect(layer, 'On', startMs, endMs, edata, pdata);
    }

    /** DMX effect setting channels 1..N to the given values (the transmitter control pulse). */
    addDmxEffect(layer: Element, startMs: number, endMs: number, values: number[], perModel = false): Element {
        const pdata = `C_BUTTON_Palette1=#000000,${BLACK_PALETTE_TAIL}`;
        const parts: string[] = [];
        if (perModel) parts.push('B_CHOICE_BufferStyle=Per Model Default Deep');
        parts.push('E_CHECKBOX_INVDMX1=0', 'E_CHECKBOX_INVDMX2=0');
        parts.push(`E_NOTEBOOK1=Channels ${values.length > 10 ? '11-20' : '1-10'}`);
        values.forEach((v, i) => parts.push(`E_SLIDER_DMX${i + 1}=${Math.max(0, Math.min(255, Math.round(v)))}`));
        return this.addEffect(layer, 'DMX', startMs, endMs, parts.join(','), pdata);
    }

    get effectCount(): number {
        return this.effectCounter;
    }

    private finalize(): void {
        while (this.palettes.firstChild) this.palettes.removeChild(this.palettes.firstChild);
        for (const p of this.paletteList) {
            const el = this.doc.createElement('ColorPalette');
            el.appendChild(this.doc.createTextNode(p));
            this.palettes.appendChild(el);
        }
        while (this.effectdb.firstChild) this.effectdb.removeChild(this.effectdb.firstChild);
        for (const e of this.effectList) {
            const el = this.doc.createElement('Effect');
            el.appendChild(this.doc.createTextNode(e));
            this.effectdb.appendChild(el);
        }
        this.setText(this.nextid, `${this.effectCounter + 1}`);
    }

    toXmlString(): string {
        this.finalize();
        const out: string[] = ['<?xml version="1.0" encoding="UTF-8"?>'];
        serializeElement(this.root, 0, out);
        return out.join('\n') + '\n';
    }

    async save(filePath: string): Promise<void> {
        await fs.writeFile(filePath, this.toXmlString(), 'utf8');
    }
}

function escapeText(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeAttr(s: string): string {
    return escapeText(s).replace(/"/g, '&quot;');
}

/** Minimal pretty printer: elements, attributes, and text (whitespace-only text between elements is dropped). */
function serializeElement(el: Element, depth: number, out: string[]): void {
    const pad = '  '.repeat(depth);
    let attrs = '';
    for (let i = 0; i < el.attributes.length; ++i) {
        const a = el.attributes[i];
        attrs += ` ${a.name}="${escapeAttr(a.value)}"`;
    }
    const kids: Element[] = [];
    let text = '';
    for (let i = 0; i < el.childNodes.length; ++i) {
        const k = el.childNodes[i];
        if (k.nodeType === 1) {
            kids.push(k as Element);
        } else if (k.nodeType === 3 || k.nodeType === 4) {
            text += k.nodeValue ?? '';
        }
    }
    if (kids.length) {
        out.push(`${pad}<${el.tagName}${attrs}>`);
        for (const k of kids) serializeElement(k, depth + 1, out);
        out.push(`${pad}</${el.tagName}>`);
    } else if (text.length) {
        out.push(`${pad}<${el.tagName}${attrs}>${escapeText(text)}</${el.tagName}>`);
    } else {
        out.push(`${pad}<${el.tagName}${attrs}/>`);
    }
}
